# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a7916bb09d3acea87837606d1d2c32838f90e498275f72f6a08b6f156e21448733b9b4b5a46639316684626fe520c7c2d90d0920faf3060c6de5ed78990487c6

test:
  secret_key_base: a187455459d2811f159dda85b6bd2d6df8e4b5ca44d4f4684cf6fe388642d73e5b25dc01ccfda853637d5b7889fbf76197ba60c4f6ab2964b25d90e02de0b072

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
